spring:
  application:
    name: admin-security-server
  security: # \u914D\u7F6E\u767B\u5F55\u7528\u6237\u540D\u548C\u5BC6\u7801
    user:
      name: wzl
      password: 123456
  boot:  # \u4E0D\u663E\u793Aadmin-security-server\u7684\u76D1\u63A7\u4FE1\u606F
    admin:
      discovery:
        ignored-services: ${spring.application.name}
server:
  port: 9301
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8002/eureka/
