server:
  port: 8002
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  client:
#    serviceUrl:
#      defaultZone: http://localhost:8003/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: false
    register-with-eureka: false