server:
  port: 9201
spring:
  profiles:
    active: dev
  application:
    name: micro-oauth2-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.175:8848
    gateway:
      routes: #\u914D\u7F6E\u8DEF\u7531\u89C4\u5219
        - id: oauth2-api-route
          uri: lb://micro-oauth2-api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: oauth2-auth-route
          uri: lb://micro-oauth2-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #\u5F00\u542F\u4ECE\u6CE8\u518C\u4E2D\u5FC3\u52A8\u6001\u521B\u5EFA\u8DEF\u7531\u7684\u529F\u80FD
          lower-case-service-id: true #\u4F7F\u7528\u5C0F\u5199\u670D\u52A1\u540D\uFF0C\u9ED8\u8BA4\u662F\u5927\u5199
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #\u914D\u7F6ERSA\u7684\u516C\u94A5\u8BBF\u95EE\u5730\u5740
  redis:
    database: 0
    port: 6379
    host: localhost
    password: 123456
secure:
  ignore:
    urls: #\u914D\u7F6E\u767D\u540D\u5355\u8DEF\u5F84
      - "/actuator/**"
      - "/auth/oauth/token"

